### ISSUE TITLE
mālā a variety of upajati?

### ISSUE THREAD

**Issue by gasyoun** [shreevatsa/sanskrit#121]
I have an issue to report about the results for the following input:
```
वने रणे शत्रुजलाग्निमध्ये
	महार्णवे पर्वतमस्तके वा ।
सुप्तं प्रमत्तं विषमस्थितं वा
	रक्षन्ति पुण्यानि पुराकृतानि ॥ ९९ ॥
```

If mālā is a variety of upajati, then why it's so red?

![upajati](https://user-images.githubusercontent.com/80761/92311997-2f564480-efc5-11ea-9604-ba91f0f203bb.PNG)

**Comment by shreevatsa** [comment]
This looks like a serious bug; in the final display it's trying to match something else. It's trying to match this:

LLLLLLLLLLLLLLG

repeated four times. That metre seems to be called śaśikalā and I don't know why it's turned up here. Will look into it sometime...

**Comment by shreevatsa** [comment]
It's trying to match https://github.com/shreevatsa/sanskrit/blob/6748493f7bf0056e7413e7d69a9c33df47ecd1ec/data/vrttaratnakara.json#L94 rather than the recognized https://github.com/shreevatsa/sanskrit/blob/6748493f7bf0056e7413e7d69a9c33df47ecd1ec/data/mishra.json#L595

— this seems the same bug as #118

**Comment by shreevatsa** [comment]
Thanks for reporting, closing as duplicate.
